1. 导入numpy库并简写为 np (★☆☆)  
>提示: import … as …  

In [1]:
import numpy as np

2. 打印numpy的版本和配置说明 (★☆☆)  
> 提示: np.__version__, np.show_config

In [3]:
print(np.__version__)
np.show_config()

1.16.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


3. 创建一个长度为10的空向量 (★☆☆)
> 提示: `np.zeros`, return the array all contains zero.

In [4]:
zv = np.zeros(10)
print(zv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小？ (★☆☆)
> 提示: 
>   * size : the number of the elements in the array
>   * itemsize : the bytes length of the array element

In [5]:
zv = np.zeros((10, 10))
print('size: %d bytes' % (zv.size * zv.itemsize))

size: 800 bytes


5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)
> 提示: `np.info()`, used to get help information of a func, class or module

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [8]:
empty_vector = np.zeros(10)
# 第5个设置为1
empty_vector[4] = 1 
print(empty_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量(★☆☆)
> 提示: `np.arange`

In [9]:
V = np.arange(10, 49)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [10]:
reversed_v = V[::-1]
print(reversed_v)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)
> 1. first generate an array contains 0 to 8
> 2. use `resharp` function

In [11]:
V = np.arange(9).reshape(3, 3)
print(V)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)
> the `np.nonzero` function return the index of the non zero element in the array

In [12]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


11. 创建一个 3x3 的单位矩阵 (★☆☆)
> A 3x3 identity matrix
> ```
[[ 1, 0, 0],
 [ 0, 1, 0],
 [ 0, 0, 1]]
```

In [14]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组 (★☆☆)

In [15]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.53180868 0.78549558 0.79522018]
  [0.01972074 0.73657973 0.43005167]
  [0.24407507 0.31459721 0.23037705]]

 [[0.90188514 0.38681348 0.28266872]
  [0.54036642 0.03518649 0.52955089]
  [0.65656421 0.15177244 0.23776594]]

 [[0.65314538 0.34081541 0.49705029]
  [0.45596853 0.8661569  0.89162143]
  [0.26314743 0.42328074 0.63597007]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [16]:
v = np.random.random((10, 10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9806457572526083 0.008698227232673328


14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [17]:
v = np.random.random(30)
avg = v.mean()
print(avg)

0.37988840352059966


15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

In [18]:
v = np.ones((3, 3))
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)

In [19]:
v = np.ones((6, 6))
v = np.pad(v, 1, 'constant', constant_values=0)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么? (★☆☆)

In [20]:
print(0*np.nan)

nan


In [21]:
print(np.nan == np.nan)

False


In [22]:
print(np.inf > np.nan)

False


In [23]:
print(np.nan - np.nan)

nan


In [24]:
print(0.3 == 3 * 0.1)

False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
> 1. generate a 1-d array [1,2,3,4]
> 2. use `np.diag` to create 2-d array

In [27]:
v = np.diag(1 + np.arange(4), k=-1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [29]:
v = np.zeros((8,8), dtype=int)
v[1::2, ::2] = 1
v[::2, 1::2] = 1
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [30]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [31]:
v = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化(★☆☆)
> 这里有两种归一化处理，一种全局最大最小值，另外一种按照每一列分别最大最小值  
> 应该第二种的归一特征应该不会影响其他列

In [10]:
v = np.random.random((6, 6))
print(v)
# way 1
v_max, v_min = v.max(), v.min()
r1 = (v - v_min)/(v_max - v_min)
print(r1)

# way 2
v_max0, v_min0 = v.max(0), v.min(0)
ranges = v_max0 - v_min0

m = v.shape[0]
diff_norm_data = v - np.tile(v_min0, (m,1))
norm_data_set1 = diff_norm_data / np.tile(ranges, (m,1))

print(norm_data_set1)

[[0.69003137 0.25532621 0.1118968  0.49330403 0.21227023 0.69866622]
 [0.00558337 0.73072196 0.24924803 0.92645812 0.20761539 0.18630234]
 [0.42172896 0.29731241 0.50182232 0.73573726 0.23043208 0.88308831]
 [0.84604681 0.89905369 0.30797273 0.49450212 0.77100012 0.2075642 ]
 [0.93170149 0.80182943 0.81867467 0.09948778 0.9266351  0.06419136]
 [0.66467386 0.63295166 0.76856678 0.06317588 0.10121101 0.42896614]]
[[0.73905044 0.26966629 0.11479468 0.526629   0.22317549 0.74837414]
 [0.         0.78298715 0.26310322 0.99433834 0.2181493  0.19513598]
 [0.44934397 0.31500198 0.53582684 0.78840255 0.24278621 0.94750866]
 [0.90751214 0.9647477  0.32651273 0.52792267 0.82647854 0.21809403]
 [1.         0.85976728 0.87795637 0.10139572 0.99452943 0.06328349]
 [0.71167001 0.67741714 0.82385108 0.062187   0.10325642 0.4571585 ]]
[[0.73905044 0.         0.         0.49824742 0.13454807 0.77479207]
 [0.         0.73850466 0.19433436 1.         0.12890874 0.14911641]
 [0.44934397 0.06522357 0.551694

23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [2]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)

In [3]:
v = np.dot(np.ones((5,3)), np.ones((3,2)))
print(v)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [5]:
v = np.arange(10)
v[(3<=v)&(v<=8)] *= -1
print(v)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


26. 下面脚本运行后的结果是什么? (★☆☆)
> 为啥前后结果不一样

In [6]:
print(sum(range(5), -1))

9


In [7]:
from numpy import *
print(sum(range(5), -1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)

In [8]:
v = np.arange(5)
v ** v

array([  1,   1,   4,  27, 256])

In [7]:
v = np.arange(5)
2 << v >> 2

array([0, 1, 2, 4, 8])

In [3]:
v = np.arange(5)
v <- v

array([False, False, False, False, False])

In [4]:
v = np.arange(5)
1j*v

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [5]:
v = np.arange(5)
v/1/1

array([0., 1., 2., 3., 4.])

In [6]:
v = np.arange(5)
v<v>v

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. 下列表达式的结果分别是什么?(★☆☆)

In [8]:
print(np.array(0) / np.array(0))

nan


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [9]:
print(np.array(0) // np.array(0))

0


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [10]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29. 如何从零位对浮点数组做舍入 ? (★☆☆)

In [11]:
v = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(v)), v))

[-5.  4. -2. -9.  6. -4. -9.  1.  6.  1.]


30. 如何找到两个数组中的共同元素? (★☆☆)

In [12]:
v1 = np.random.randint(0, 10, 10)
v2 = np.random.randint(0, 10, 10)
print(np.intersect1d(v1, v2))

[0 3 7]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [14]:
defaults = np.seterr(all='ignore')
v = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗? (★☆☆)

In [15]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. 如何得到昨天，今天，明天的日期? (★☆☆)

In [16]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('Yesterday is ', yesterday)
print('Today is ', today)
print('Tomorrow is ', tomorrow)


Yesterday is  2019-06-20
Today is  2019-06-21
Tomorrow is  2019-06-22


34. 如何得到所有与2016年7月对应的日期？ (★★☆)

In [18]:
v = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)

In [19]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)

In [21]:
v = np.random.uniform(0, 10, 10)
print(v)
print(v - v%1)
print(np.floor(v))
print(v.astype(int))
print(np.ceil(v) - 1)
print(np.trunc(v))

[3.68704895 2.64349566 6.8672185  8.61802741 9.96122828 0.24174461
 5.72547933 7.28264261 7.93621915 9.36758942]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3 2 6 8 9 0 5 7 7 9]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)

In [22]:
v = np.zeros((5,5))
v += np.arange(5)
print(v)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)

In [2]:
def generate():
    for x in range(10):
        yield x

v = np.fromiter(generate(), dtype=float, count=-1)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)

In [3]:
v = np.linspace(0, 1, 11, endpoint=False)[1:]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序 (★★☆)

In [4]:
v = np.random.random(10)
print(v)
v.sort()
print(v)

[0.88735466 0.67448082 0.70716609 0.15003484 0.21767853 0.37902043
 0.87191868 0.59519264 0.40722987 0.78681261]
[0.15003484 0.21767853 0.37902043 0.40722987 0.59519264 0.67448082
 0.70716609 0.78681261 0.87191868 0.88735466]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)

In [5]:
v = np.arange(10)
np.add.reduce(v)

45

42. 对于两个随机数组A和B，检查它们是否相等(★★☆)

In [6]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
e1 = np.array_equal(a, b)
print(e1)
e2 = np.allclose(a,b)
print(e2)

False
False


43. 创建一个只读数组(read-only) (★★☆)

In [8]:
v = np.zeros(10)
v.flags.writeable = False
v[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)

In [11]:
v = np.random.random((10,2))
x,y = v[:,0], v[:,1]
# 距离
r = np.sqrt(x**2, y**2)
# 角度
t = np.arctan2(y,x)
print(r)
print(t)

[0.39676937 0.43422024 0.94488514 0.37967117 0.20801399 0.3383388
 0.76177745 0.9213726  0.07867197 0.79865613]
[1.05435359 0.78832439 0.51466034 1.11865018 0.20219041 1.12636779
 0.75289351 0.47756715 1.40597893 0.72079018]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)

In [12]:
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

[0.         0.51796071 0.71179704 0.77536585 0.17114683 0.35596543
 0.2794372  0.72704592 0.50707695 0.74092865]
