## Data Transformation

In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

### Removing Duplicates

In [4]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1,1,2,3,3,4,4]})

In [5]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [6]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [7]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [8]:
data['v1'] = range(7)

In [9]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [10]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [11]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon',
         'pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [12]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [13]:
meat_to_animal = {
      'bacon': 'pig',
      'pulled pork': 'pig',
      'pastrami': 'cow',
      'corned beef': 'cow',
      'honey ham': 'pig',
      'nova lox': 'salmon'
}

In [14]:
lowercased = data['food'].str.lower()

In [15]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [16]:
data['animal'] = lowercased.map(meat_to_animal)

In [17]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [18]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [19]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [20]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [22]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [23]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [24]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [25]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [26]:
transform = lambda x: x[:4].upper()

In [27]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [28]:
data.index = data.index.map(transform)

In [29]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [30]:
data.index

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [31]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [32]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [33]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [34]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

Discretization and Binning

In [2]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [3]:
bins = [18, 25, 35, 60, 100]

In [4]:
cats = pd.cut(ages, bins)

In [5]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [6]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [7]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [8]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [9]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [10]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [11]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [12]:
data = np.random.rand(20)

In [13]:
pd.cut(data, 4, precision=2)

[(0.74, 0.97], (0.74, 0.97], (0.74, 0.97], (0.028, 0.26], (0.028, 0.26], ..., (0.74, 0.97], (0.26, 0.5], (0.74, 0.97], (0.74, 0.97], (0.028, 0.26]]
Length: 20
Categories (4, interval[float64]): [(0.028, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.97]]

In [14]:
data = np.random.randn(1000)

`qcut`方法会将样本数据平均分成不同的区间范围,每个区间样本数量相同,而`cut`方法则是根据样本最大值和最小值将范围平均切分

In [15]:
cats = pd.qcut(data, 4)

In [16]:
cats

[(-0.0221, 0.624], (-0.0221, 0.624], (-0.648, -0.0221], (-3.073, -0.648], (0.624, 3.184], ..., (0.624, 3.184], (-0.0221, 0.624], (-3.073, -0.648], (-0.648, -0.0221], (-3.073, -0.648]]
Length: 1000
Categories (4, interval[float64]): [(-3.073, -0.648] < (-0.648, -0.0221] < (-0.0221, 0.624] < (0.624, 3.184]]

In [17]:
pd.value_counts(cats)

(0.624, 3.184]       250
(-0.0221, 0.624]     250
(-0.648, -0.0221]    250
(-3.073, -0.648]     250
dtype: int64

In [18]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

[(-0.0221, 1.182], (-0.0221, 1.182], (-1.238, -0.0221], (-3.073, -1.238], (-0.0221, 1.182], ..., (-0.0221, 1.182], (-0.0221, 1.182], (-1.238, -0.0221], (-1.238, -0.0221], (-3.073, -1.238]]
Length: 1000
Categories (4, interval[float64]): [(-3.073, -1.238] < (-1.238, -0.0221] < (-0.0221, 1.182] < (1.182, 3.184]]

In [19]:
pd.value_counts(pd.qcut(data,  [0, 0.1, 0.5, 0.9, 1]))

(-0.0221, 1.182]     400
(-1.238, -0.0221]    400
(1.182, 3.184]       100
(-3.073, -1.238]     100
dtype: int64

### Detecting and Filtering Outliers

In [20]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [21]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.015156     0.013030    -0.024843    -0.013124
std       0.997509     1.006407     1.003656     0.999851
min      -3.602961    -3.368741    -3.386918    -2.948855
25%      -0.734141    -0.622566    -0.698036    -0.693395
50%       0.012659    -0.010764    -0.026436    -0.057675
75%       0.640309     0.665676     0.606453     0.680790
max       3.371539     2.967103     2.938080     2.802230

In [22]:
 col = data[2]

In [23]:
col[np.abs(col) > 3]

18    -3.234909
976   -3.386918
Name: 2, dtype: float64

In [24]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
18   0.287607  0.427816 -3.234909 -0.346359
247  3.117574 -1.080841  0.395406  1.034339
251 -0.687649 -3.127758 -0.200266  1.504933
519  0.945152 -3.368741 -0.913102  1.747557
570 -3.602961  0.295982  0.787812  2.190970
932  3.104406 -0.299415 -0.566137 -0.552706
963  3.371539  1.990655 -2.927038  0.960636
976  0.154650 -0.309535 -3.386918 -0.208376

In [25]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [26]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0  1.0
1 -1.0 -1.0  1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

Permutation and Random Sampling

In [27]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5,4)))

In [28]:
sampler = np.random.permutation(5)

In [29]:
sampler

array([3, 1, 4, 0, 2])

In [30]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [31]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [32]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15

In [33]:
choices = pd.Series([5,7 -1, 6, 4])

In [34]:
draws = choices.sample(n=10, replace=True)

In [35]:
draws

3    4
3    4
2    6
3    4
1    6
0    5
1    6
2    6
0    5
3    4
dtype: int64

### Computing Indicator/Dummy Variables

In [36]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})

In [37]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [38]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [39]:
df_with_dummy = df[['data1']].join(dummies)

In [40]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [41]:
mnames = ['movie_id', 'title', 'genres']

In [43]:
movies = pd.read_table('../data_sets/movie_lens_1M/movies.dat', sep='::', header=None, names=mnames)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [44]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [45]:
all_genres = []

In [46]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [47]:
genres = pd.unique(all_genres)

In [48]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [49]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [50]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [51]:
gen = movies.genres[0]

In [52]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [53]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [55]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [56]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [57]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [58]:
np.random.seed(12345)

In [59]:
values = np.random.rand(10)

In [60]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [61]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [62]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0